[package]
name = "elden-ring-lore-pickup"
version = "0.8.1"
edition = "2021"
description = "Show Elden Ring item lore automatically when an item is acquired."
repository = "https://github.com/henryday22/EldenRingLorePickup"

[lib]
name = "EldenRingLorePickup"
crate-type = ["cdylib"]

[dependencies]
retour = "0.3"
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_Graphics_GdiPlus",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
    "Win32_UI_Input_XboxController",
    "Win32_UI_WindowsAndMessaging",
] }

[dependencies.windows]
version = "0.62"
features = [
    "Win32_Foundation",
    "Win32_System_LibraryLoader",
    "Win32_System_SystemServices",
]

[profile.release]
lto = "thin"
codegen-units = 1
