const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const {resolve}=require('node:path');
const {pathToFileURL}=require('node:url');
const directory=process.argv[2]||'previews';
(async()=>{
 const browser=await chromium.launch({headless:true,channel:process.env.LOREPICKUP_BROWSER_CHANNEL||'msedge',args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[]; page.on('pageerror',e=>errors.push(e.message));
 await page.goto(pathToFileURL(resolve(directory,'journal.html')).href);
 await page.selectOption('#profile','strength');
 assert.match(await page.textContent('#progress'),/^2 \/ 2503/);
 assert.equal(await page.locator('#list button').count(),2);
 await page.fill('#search','Moss');assert.equal(await page.locator('#list button').count(),1);
 assert.match(await page.textContent('#title'),/Herb/);
 await page.screenshot({path:resolve(directory,'journal-desktop.png'),fullPage:true});
 await page.fill('#search','');await page.selectOption('#category','Weapons');
 assert.equal(await page.locator('#list button').count(),1);assert.match(await page.textContent('#title'),/Halberd/);
 await page.selectOption('#category','');await page.selectOption('#profile','faith');
 assert.equal(await page.locator('#list button').count(),1);assert.match(await page.textContent('#title'),/incantation/);
 await page.fill('#search','does-not-exist');assert.match(await page.textContent('#empty'),/No cards match/);
 await page.fill('#search','');await page.selectOption('#profile','strength');
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.screenshot({path:resolve(directory,'journal-mobile.png'),fullPage:true});
 assert.deepEqual(errors,[]);console.log('Journal checks passed: separate profiles/counts, name/material search, categories, empty state and mobile layout.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
